language: ruby
before_install: "gem install bundler"
script: "bundle exec rake"
notifications:
  email:
    - alessiorocco@nebulab.it
branches:
  only:
    - master
rvm:
  - 2.2.0
  - 2.1.0
  - 2.0.0
